version: '3'

services:
  server_4001:
    image: midas_broadcast:latest
    environment:
      - PORTS=4001 4000 4002
    ports:
      - 4001:4001
  server_4002:
    image: midas_broadcast:latest
    environment:
      - PORTS=4002 4000 4001
    ports:
      - 4002:4002
